version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name cicd-handson-app-work-5 --s3-location s3://cicd-artifact-bucket-work-5-06-12/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src